import HeaderTop from "@/src/components/HeaderTop";
import "../app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HeaderMain from "@/src/components/HeaderMain";
import Navbar from "@/src/components/Navbar";
// import { ApolloProvider } from '@apollo/client'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <ApolloProvider client={client}> */}
        <HeaderTop />
        <HeaderMain />
        <Navbar />
        {children}
        {/* </ApolloProvider> */}
      </body>
    </html>
  );
}
