"use client"; 

import HeaderTop from "@/src/components/HeaderTop";
import "../app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HeaderMain from "@/src/components/HeaderMain";
import Navbar from "@/src/components/Navbar";
// import { ApolloProvider } from '@apollo/client'
import { useEffect, useState } from "react";
import LoginForm from "../components/LoginForm";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [authenticated, setAuthenticated] = useState(false);

  useEffect(() => {
    // Check for a valid JWT token in local storage
    const token = localStorage.getItem("token");

    if (token) {
      axios.defaults.headers.common["Authorization"] = `Bearer ${token}`;
      setAuthenticated(true);
    }
  }, []);

  const handleLogin = () => {
    setAuthenticated(true);
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ApolloProvider client={client}> */}
        {authenticated ? (
          <>
            <HeaderTop />
            <HeaderMain />
            <Navbar />
            {children}
          </>
        ) : (
          <LoginForm onLogin={handleLogin} />
        )}

        {/* </ApolloProvider> */}
      </body>
    </html>
  );
}
